import { createFileRoute } from "@tanstack/react-router";
import { Compass, Eye } from "lucide-react";
import { PageHero, Reveal } from "@/components/SiteChrome";
import { images } from "@/lib/site-data";

export const Route = createFileRoute("/our-story")({
  staticData: { sitemap: true },
  head: () => ({ meta: [
    { title: "Our Story | PYAR Architects" }, { name: "description", content: "Meet the philosophy, people and journey behind Bangalore design studio PYAR Architects." },
    { property: "og:title", content: "Our Story | PYAR Architects" }, { property: "og:description", content: "Youthful vision and enduring design, from 2018 to today." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: StoryPage,
});

function StoryPage() {
  const timeline = [["2018","PYAR begins with a belief that ambitious design can remain deeply human."],["2020","The practice expands into interiors and integrated project delivery."],["2023","A growing portfolio reaches across Bangalore and the wider Karnataka landscape."],["Present","Architecture, interiors, construction and prefabrication move forward as one studio."]];
  return <><PageHero eyebrow="The studio" title="A young practice with a lasting point of view." image={images.courtyard}/><section className="mx-auto max-w-7xl px-5 py-28 sm:px-8 lg:py-36"><Reveal><p className="label">Why PYAR</p><div className="mt-6 grid gap-8 lg:grid-cols-2"><h2 className="display-title">Perfect Youths In<br/>Architectural Reign.</h2><div className="space-y-5 text-base leading-8 text-muted-foreground"><p>Our name carries our intent: fresh thinking, exacting craft and the confidence to make spaces with presence.</p><p>Based in Bangalore, we work across architecture, interior design, construction and prefabricated solutions—connecting every discipline through one clear vision.</p></div></div></Reveal></section><section className="bg-surface py-28"><div className="mx-auto grid max-w-7xl gap-5 px-5 sm:px-8 md:grid-cols-2"><Reveal><article className="glass-panel min-h-80 p-8 sm:p-10"><Compass className="size-8 stroke-1 text-primary"/><p className="label mt-16">Our mission</p><h2 className="mt-4 font-display text-3xl">Make thoughtful design attainable, buildable and enduring.</h2></article></Reveal><Reveal><article className="glass-panel min-h-80 p-8 sm:p-10"><Eye className="size-8 stroke-1 text-primary"/><p className="label mt-16">Our vision</p><h2 className="mt-4 font-display text-3xl">Shape a new architectural language rooted in India and open to the world.</h2></article></Reveal></div></section><section className="mx-auto max-w-7xl px-5 py-28 sm:px-8"><Reveal><p className="label">The collective</p><h2 className="mt-5 font-display text-5xl">People behind the practice.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{["Lead Architect","Design Principal","Project Architect"].map((role,i)=><Reveal key={role}><article className="group"><div className="relative h-96 overflow-hidden bg-muted"><img src={[images.residence,images.interior,images.commercial][i]} alt={`${role} at PYAR Architects`} loading="lazy" className="h-full w-full object-cover opacity-50 grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0"/><div className="absolute inset-0 bg-image-overlay"/></div><div className="border-x border-b border-border p-5"><h3 className="font-display text-2xl">PYAR Studio</h3><p className="mt-1 text-xs uppercase tracking-[0.18em] text-primary">{role}</p></div></article></Reveal>)}</div></section><section className="border-t border-border py-28"><div className="mx-auto max-w-5xl px-5 sm:px-8"><Reveal><p className="label">Our journey</p><h2 className="mt-5 font-display text-5xl">2018 → Present</h2></Reveal><div className="mt-14">{timeline.map(([year,text])=><Reveal key={year}><div className="grid gap-4 border-t border-border py-8 sm:grid-cols-[180px_1fr]"><span className="font-display text-3xl text-primary">{year}</span><p className="max-w-2xl leading-7 text-muted-foreground">{text}</p></div></Reveal>)}</div></div></section></>;
}